/* The human-readable proof: a markdown report of every mode vs the baseline. */
import { CATEGORIES, VOLATILE_FIELDS, formatGitDiff, type Category, type Diff } from './compare'
import { MODE_SETUP, PROMPT, type Mode, type RunResult } from './run-claude'

export interface ModeResult {
  mode: Exclude<Mode, 'baseline'>
  known: Category[]
  run: RunResult
  diffs: Diff[]
}

const cellText = (s: string) => s.replace(/\|/g, '\\|').replace(/\s+/g, ' ')
const clip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n)}…` : s)

function verdict(r: ModeResult, c: Category): string {
  const differs = r.diffs.some(d => d.category === c)
  const known = r.known.includes(c)
  if (differs) return known ? 'differs (known)' : '**differs (UNEXPECTED)**'
  return known ? '**equal (expected to differ)**' : 'equal'
}

function firstDifference(diffs: Diff[]): string {
  const d = diffs[0]
  if (!d) return ''
  const side = (v: unknown) => (v === undefined ? '(absent)' : JSON.stringify(v))
  let what: string
  if (typeof d.baseline === 'string' && typeof d.capture === 'string' && (d.baseline.includes('\n') || d.capture.includes('\n'))) {
    const a = new Set(d.baseline.split('\n'))
    const b = new Set(d.capture.split('\n'))
    what = `-${[...a].filter(l => !b.has(l)).length} / +${[...b].filter(l => !a.has(l)).length} lines`
  } else {
    what = `${clip(side(d.baseline), 70)} → ${clip(side(d.capture), 70)}`
  }
  const more = diffs.length > 1 ? ` (+${diffs.length - 1} more)` : ''
  return `\`${cellText(d.path)}\`: ${cellText(what)}${more}`
}

export function buildReport({ claudeVersion, baseline, results }: { claudeVersion: string; baseline: RunResult; results: ModeResult[] }): string {
  const L: string[] = []
  const ok = (r: ModeResult) => CATEGORIES.every(c => r.diffs.some(d => d.category === c) === r.known.includes(c))
  L.push('# cc-tap capture equivalence report', '')
  L.push(`- Date: ${new Date().toISOString()}`)
  L.push(`- Claude Code: ${claudeVersion}`)
  L.push(`- Node.js: ${process.version} (${process.platform})`)
  L.push(`- Generated by: \`npm run test:equivalence\` (test/equivalence/)`, '')

  L.push('## Question', '')
  L.push('Does what cc-tap stores (inspector.db + payloads) equal what Claude Code sends to Anthropic when cc-tap is not involved?', '')

  L.push('## Scenario', '')
  L.push(`The real \`claude\` CLI runs \`claude -p "${PROMPT}" --allowedTools Bash\` against a fake Anthropic API, in a clean environment (own HOME, fake API key, \`CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1\`, shared working directory). The fake API answers the main loop with 429, then 529 (both retried), then a thinking block + a Bash \`tool_use\`, then the final text. No network, no real API call.`, '')
  L.push('| Run | Setup |', '|---|---|')
  L.push(`| baseline (no cc-tap) | ${MODE_SETUP.baseline} |`)
  for (const r of results) L.push(`| ${r.mode} | ${MODE_SETUP[r.mode]} |`)
  L.push('')
  L.push(`Baseline wire traffic (/v1/messages): ${baseline.wire.map(c => c.response.status).join(' → ')}; exit code ${baseline.exitCode}.`, '')
  L.push('Each mode\'s stored captures are compared attempt by attempt to the baseline\'s wire requests and responses: request body fields, the anthropic-beta set, the status of every attempt, and the assembled response.', '')

  L.push('## Result', '')
  L.push(`| Field | ${results.map(r => r.mode).join(' | ')} |`, `|---|${results.map(() => '---').join('|')}|`)
  for (const c of CATEGORIES) L.push(`| ${c} | ${results.map(r => verdict(r, c)).join(' | ')} |`)
  L.push(`| **matches expectation** | ${results.map(r => (ok(r) ? 'yes' : '**NO**')).join(' | ')} |`, '')
  for (const r of results) {
    const differing = CATEGORIES.filter(c => r.diffs.some(d => d.category === c))
    L.push(`- **${r.mode}**: ${differing.length === 0 ? 'equivalent to the baseline on every field.' : `differs on ${differing.join(', ')}.`}${r.known.length ? ' Expected: proxy mode is documented as not equivalent.' : ''}`)
  }
  L.push('')

  for (const r of results) {
    L.push(`## ${r.mode} vs baseline`, '')
    L.push(`${r.run.captures.length} captures stored for ${r.run.wire.length} /v1/messages attempts on the wire; statuses ${r.run.captures.map(c => c.row.status_code).join(' → ')}; exit code ${r.run.exitCode}.`, '')
    L.push('| Field | Result | First difference |', '|---|---|---|')
    for (const c of CATEGORIES) L.push(`| ${c} | ${verdict(r, c)} | ${firstDifference(r.diffs.filter(d => d.category === c))} |`)
    L.push('')
    if (r.diffs.length) {
      L.push('<details><summary>Full diff</summary>', '', '`-` baseline (no cc-tap), `+` what cc-tap stored.', '')
      L.push('```diff', formatGitDiff(r.diffs), '```', '', '</details>', '')
    }
  }

  L.push('## Normalized fields', '')
  L.push('Only these are normalized before comparing; everything else must be equal.', '')
  L.push('| Field | Why |', '|---|---|')
  for (const v of VOLATILE_FIELDS) L.push(`| ${cellText(v.field)} | ${cellText(v.why)} |`)
  L.push('')
  return L.join('\n')
}
